# Generated by Django 3.1 on 2020-08-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='site_mane',
            new_name='site_name',
        ),
    ]
